#!/bin/sh

# Adapted from: https://github.com/git/git/blob/master/templates/hooks--pre-push.sample

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

# Refer to https://git-scm.com/docs/githooks#:~:text=pre-push for argument usage
while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"
		then
			# New branch, examine all commits
			range="$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check for WIP commit
		cd server; yarn lint
		if [ $? -ne 0 ]
		then
			echo >&2 "lint failed, not pushing"
			exit 1
		fi
		echo "no lint errors found"
		cd client; yarn lint
		if [ $? -ne 0 ]
		then
			echo >&2 "lint failed, not pushing"
			exit 1
		fi
		echo "no lint errors found"
	fi
done

exit 0
